# Call packages

library(phyloseq)
library(ggplot2)
library(vegan)
library(tidyverse)

# Set Working directory
setwd('C:/Users/gecre/OneDrive/Dada2')


# Build data.frame 
sample.out <- rownames(tax_all)
sample.out

subject <- sapply(strsplit(sample.out, "_"), `[`, 1)
subject

method <- substr(subject, 1,4)
method

subject <- substr(subject,5,7)
subject

type <- substr(subject, 8,20)
type

samdf <- data.frame(Subject=subject, Method=method, Type=type)
rownames(samdf) <- sample.out

# Phyloseq object with controls
physeq_275x280 <- phyloseq(otu_table(nc_all, taxa_are_rows=FALSE), 
                           sample_data(samdf), 
                           tax_table(tax_all))

saveRDS(physeq_275x280, "C:/Users/gecre/OneDrive/Dada2/physeq_275x280.rds")


# Phyloseq object without controls
ps_noCtrl <- prune_samples(sample_names(ps) != "Kit1PosCtrlPC_R1.fastq.gz", ps) 
ps_noCtrl <- prune_samples(sample_names(ps_noCtrl) != "Kit2PosCtrlPC_R1.fastq.gz", ps_noCtrl)
ps_noCtrl <- prune_samples(sample_names(ps_noCtrl) != "Kit3PosCtrlPC_R1.fastq.gz", ps_noCtrl)
ps_noCtrl <- prune_samples(sample_names(ps_noCtrl) != "Kit4PosCtrlPC_R1.fastq.gz", ps_noCtrl)
ps_noCtrl <- prune_samples(sample_names(ps_noCtrl) != "Kit1NegCtrlNC_R1.fastq.gz", ps_noCtrl)
ps_noCtrl <- prune_samples(sample_names(ps_noCtrl) != "Kit2NegCtrlNC_R1.fastq.gz", ps_noCtrl)
ps_noCtrl <- prune_samples(sample_names(ps_noCtrl) != "Kit3NegCtrlNC_R1.fastq.gz", ps_noCtrl)
ps_noCtrl <- prune_samples(sample_names(ps_noCtrl) != "Kit4NegCtrlNC_R1.fastq.gz", ps_noCtrl)
ps_noCtrl
saveRDS(ps_noCtrl, "C:/Users/gecre/OneDrive/Dada2/ps_noCtrl.rds") #The following pipeline was performed using the datasets with and without controls.

# Filtering data for "Bacteria"
physeq_275x280_bacteria <- subset_taxa(physeq_275x280, Kingdom == "Bacteria")
saveRDS(physeq_275x280_bacteria, "C:/Users/gecre/OneDrive/Dada2/physeq_275x280_bacteria.rds")

# Reading RDS
physeq<- readRDS('C:/Users/gecre/OneDrive/Dada2/RDS files/physeq_275x280_bacteria.rds')

# Adding rooted tree for Unifrac analysis
library('ape')
random_tree <- rtree(ntaxa(physeq), rooted = T, tip.label = taxa_names(physeq))
physeq_tree <- merge_phyloseq(physeq, random_tree)

# Rarefy data without replacement
physeq_tree_rarefied <- rarefy_even_depth(physeq_tree, rngseed=1, sample.size = 0.9*min(sample_sums(physeq_tree)), replace = F )
sample.sums1 <- sample_sums(x = physeq_tree)
sample.sums2 <- sample_sums(x = physeq_tree_rarefied)

# Plotting Alpha diversity
source('ColorScript.R')
a_rarefied<- plot_richness(physeq_tree_rarefied, x="Method", measures=c("Shannon", "Observed"), color="Method")
a_rarefied <- a_rarefied + geom_boxplot(data = a_rarefied$data, aes(x = Method, y = value)) +
              scale_color_manual(values = kitcols) + theme_set(theme_bw()) +
              theme(legend.title = element_text(size = 12, face = 'bold')) +
              theme(legend.text = element_text(size = 12)) +
              theme(axis.title.x = element_text(size = 14, face = 'bold')) +
              theme(axis.title.y = element_text(size = 14, face = 'bold')) +
              theme(axis.text.x = element_text(size = 11, face = 'bold'))
a_rarefied                              
ggsave(a_rarefied, filename = "alpha_diversity.tiff", path = 'C:/Users/gecre/OneDrive/Dada2/alpha-diversity/paper_figures/', dpi =400, height = 8, width = 10 )

# Comparing alpha diversity indexes by Method

# Shannon
results_rarefied = estimate_richness(physeq_tree_rarefied, measures = 'Shannon')
d_rarefied = sample_data(physeq_tree_rarefied)

M1_r = results_rarefied[d_rarefied[,'Method'] == 'Kit1',]
M2_r = results_rarefied[d_rarefied[,'Method'] == 'Kit2',]
M3_r = results_rarefied[d_rarefied[,'Method'] == 'Kit3',]
M4_r = results_rarefied[d_rarefied[,'Method'] == 'Kit4',]

kruskal.test(M1_r, M2_r, M3_r, M4_r)

# Observed OTUs
results_rarefied2 = estimate_richness(physeq_tree_rarefied, measures = 'Observed')
d_rarefied2 = sample_data(physeq_tree_rarefied)

M1_r2 = results_rarefied2[d_rarefied2[,'Method'] == 'Kit1',]
M2_r2 = results_rarefied2[d_rarefied2[,'Method'] == 'Kit2',]
M3_r2 = results_rarefied2[d_rarefied2[,'Method'] == 'Kit3',]
M4_r2 = results_rarefied2[d_rarefied2[,'Method'] == 'Kit4',]

kruskal.test(M1_r2, M2_r2, M3_r2, M4_r2)

# Beta-diversity - NMDS #

# Bray-Curtis 
source('ColorScript.R')

bray_dist_rarefied = phyloseq::distance(physeq_tree_rarefied, method="bray")
ordination = ordinate(physeq_tree_rarefied, method="NMDS", distance=bray_dist_rarefied)

p_rarefied <- plot_ordination(physeq = physeq_tree_rarefied, ordination = ordination, color = "Method", shape = "Type")+
              scale_shape_manual(values=c('CtrlNC'=15, 'CtrlPC'=17, 'Feces'=19)) +
              geom_point(size=4, alpha=0.5) + ggtitle("NMDS on Bray-Curtis - stress: 0.129")+
              scale_color_manual(values = kitcols) + theme(legend.title = element_text( size = 12, face = 'bold')) +
              theme(legend.text = element_text(size = 12)) +
              theme(axis.title.x = element_text( size = 14, face = 'bold')) +
              theme(axis.title.y = element_text( size = 14, face = 'bold')) 

p_rarefied
ggsave(p_rarefied, filename = "Bray_NMDS_r_final.tiff", path = 'C:/Users/gecre/OneDrive/Dada2/beta-diversity', dpi =400, height = 8, width = 10 )

# Unifrac 
wunifrac_dist_rarefied = phyloseq::distance(physeq_tree_rarefied, method="unifrac", weighted=T)
ordination2 = ordinate(physeq_tree_rarefied, method="NMDS", distance=wunifrac_dist_rarefied)

p2_rarefied <- plot_ordination(physeq_tree_rarefied, ordination2, color = "Method", shape = "Type" )+
               geom_point(size=5, alpha=0.5) + 
               ggtitle("NMDS on Weighted Unifrac distance")+
               scale_color_manual(values = kitcols) + theme(legend.title = element_text(size = 12, face = 'bold')) +
               theme(legend.text = element_text(size = 12)) +
               theme(axis.title.x = element_text(size = 14, face = 'bold')) +
               theme(axis.title.y = element_text(size = 14, face = 'bold'))
p2_rarefied
ggsave(p2_rarefied, filename = "weighted_NMDS_rarefied.tiff", path = 'C:/Users/gecre/OneDrive/Dada2/beta-diversity/paper_figures/', dpi =400, height = 8, width = 10 )

# Beta-diversity on PCoA #

# Bray-Curtis
bray_dist_rarefied = phyloseq::distance(physeq_tree_rarefied, method="bray")
ordination3 = ordinate(physeq_tree_rarefied, method="PCoA", distance=bray_dist_rarefied)

p3_rarefied <- plot_ordination(physeq = physeq_tree_rarefied, ordination = ordination3, color = "Method", shape = "Type" )
p3_rarefied = p3_rarefied + geom_point(size=5, alpha=0.5)
p3_rarefied = p3_rarefied + ggtitle("PCoA on Bray-Curtis distance") +
              scale_color_manual(values = kitcols) + theme(legend.title = element_text(size = 12, face = 'bold')) +
              theme(legend.text = element_text(size = 12)) +
              theme(axis.title.x = element_text(size = 14, face = 'bold')) +
              theme(axis.title.y = element_text(size = 14, face = 'bold'))

p3_rarefied
ggsave(p3_rarefied, filename = "Bray_PCoA_rarefied.tiff", path = 'C:/Users/gecre/OneDrive/Dada2/beta-diversity/paper_figures/', dpi =400, height = 8, width = 10 )

# Weighted Unifrac 
wunifrac_dist_rarefied = phyloseq::distance(physeq_tree_rarefied, method="unifrac", weighted=T)
ordination4 = ordinate(physeq_tree_rarefied, method="PCoA", distance=wunifrac_dist_rarefied)

p4_rarefied <- plot_ordination(physeq = physeq_tree_rarefied, ordination = ordination4, color = "Method", shape = "Type" ) +
               geom_point(size=5, alpha=0.5) + ggtitle("PCoA on Weighted Unifrac distance") +
               scale_color_manual(values = kitcols) + theme(legend.title = element_text(size = 12, face = 'bold')) +
               theme(legend.text = element_text(size = 12)) +
               theme(axis.title.x = element_text(size = 14, face = 'bold')) +
               theme(axis.title.y = element_text(size = 14, face = 'bold'))

p4_rarefied
ggsave(p4_rarefied, filename = "Wunifrac_PCoA_rarefied.tiff", path = 'C:/Users/gecre/OneDrive/Dada2/beta-diversity/paper_figures/', dpi =400, height = 8, width = 10 )

# Permanova 
library(vegan)
metadata1_rarefied <- as(sample_data(physeq_tree_rarefied), 'data.frame')

adonis(distance(physeq_tree_rarefied, method = 'bray') ~ Method, data = metadata1_rarefied)
adonis(distance(physeq_tree_rarefied, method = 'wunifrac') ~ Method, data = metadata1_rarefied)

#Taxonomic plots #

# Phylum

#normalizing data
ps.top20 <- transform_sample_counts(physeq_tree_rarefied, function(OTU) OTU/sum(OTU))

# Computing the phylum
ps.phylum = tax_glom(ps.top20, taxrank = "Phylum", NArm = FALSE)
top.20 <- names(sort(taxa_sums(ps.phylum), TRUE)[1:20])
phylum20 <- prune_taxa(top.20, ps.phylum)

# Plotting phylum
library(RColorBrewer)
phylum <- plot_bar(phylum20, x= "Subject", fill = 'Phylum', ) +
          facet_wrap(~ Method, scales = "free_x", nrow = 1 ) +
          theme(legend.title = element_text(size = 12, face = 'bold')) +
          theme(legend.text = element_text(size = 12)) +
          theme(axis.title.x = element_text(size = 16, face = 'bold')) +
          theme(axis.title.y = element_text(size = 16, face = 'bold'))

phylum
ggsave (phylum, filename = "phylum_final.tiff", path = 'C:/Users/gecre/OneDrive/Dada2/abundance/', dpi =400, height = 8, width = 10 )

# Genus #

# Transforming data
ps.top15 <- transform_sample_counts(physeq_tree_rarefied, function(OTU) OTU/sum(OTU))

# Computing the 15 most relative abundant genera
ps.genus = tax_glom(ps.top15, taxrank = "Genus", NArm = FALSE)
top.15 <- names(sort(taxa_sums(ps.genus), TRUE)[1:15])
genus15 <- prune_taxa(top.15, ps.genus)

# Plotting genus
genus <- plot_bar(genus15, x= "Subject", fill = 'Genus', ) +
         facet_wrap(~ Method, scales = "free_x", nrow = 1 ) +
         scale_fill_viridis_d(option = "plasma", na.value = "gray35")+
         theme(legend.title = element_text(size = 12, face = 'bold')) +
         theme(legend.text = element_text(size = 12)) +
         theme(axis.title.x = element_text(size = 14, face = 'bold')) +
         theme(axis.title.y = element_text(size = 14, face = 'bold')) +
         geom_bar(stat="identity", position = 'fill')

genus
ggsave (genus, filename = "genus.tiff", path = 'C:/Users/gecre/OneDrive/Dada2/abundance/', dpi =400, height = 8, width = 10)

# Removing Unassigned Genera
genus_UN = subset_taxa(genus15, Genus != "unassigned")
genusUN <- plot_bar(genus_UN, x= "Subject", fill = 'Genus', ) +
          facet_wrap(~ Method, scales = "free_x", nrow = 1 ) +
          scale_fill_viridis_d(option = "plasma", na.value = "gray35")+
          theme(legend.title = element_text(size = 12, face = 'bold')) +
          theme(legend.text = element_text(size = 12, face = "italic")) +
          theme(axis.title.x = element_text(size = 14, face = 'bold')) +
          theme(axis.title.y = element_text(size = 14, face = 'bold')) +
          geom_bar(stat="identity", position = "fill")
genusUN

#Final plot
genus_final <- read.table(file = 'Genus_final.txt', header = T)
genus_final <- as.data.frame(genus_final)

genus <- ggplot(genus_final, aes(fill=reorder(Genus, Abundance), y = Abundance, x = Sample)) +
         geom_bar(position = 'fill', stat = "identity")+
         facet_wrap(~ Method, scales = "free_x", nrow = 1 ) +
         theme(legend.title = element_text(size = 12, face = 'bold')) +
         theme(legend.text = element_text(size = 12, face = "italic")) +
         theme(axis.title.x = element_text(size = 14, face = 'bold')) +
         theme(axis.title.y = element_text(size = 14, face = 'bold')) +
         theme(axis.text.x = element_text(size = 16, angle = 90)) +
         guides(fill=guide_legend(nrow=20)) +
    '    scale_fill_brewer(palette =  'Spectral')  
genus
ggsave (genus, filename = "genus_final.tiff", path = 'C:/Users/gecre/OneDrive/Dada2/abundance/', dpi =400, height = 8, width = 10)


# Negative Controls #

# Normalize data
physeq_tree_rarefied_transformed <- transform_sample_counts(physeq_tree_rarefied, function(OTU) OTU/sum(OTU))

# Subset out just the negative controls
ps_nc = subset_samples(physeq_tree_rarefied_transformed, Type== "CtrlNC")

# How abundant are the SVs in the negative controls?	
plot(sort(taxa_sums(ps_nc), TRUE), type = "p")

# What's in them?	
top.nc.20 <- names(sort(taxa_sums(ps_nc), TRUE)[1:20])
genusnc20 <- prune_taxa(top.nc.20, ps_nc)

# Exporting table #
tax <- tax_table(genusnc20)
tax <- psmelt(tax)
write.csv(tax, file='taxa_NC.csv')

otus <- otu_table(genusnc20)
otus <- psmelt(otus)
write.csv(otus, file='otu_NC.csv') #Taxonomic plot of negative controls were performed in Excel


# Positive Controls #

# Subset out just the positive controls
ps_pc = subset_samples(physeq_tree_rarefied_transformed, Type== "CtrlPC")

# How abundant are the SVs in the negative controls?	
plot(sort(taxa_sums(ps_pc), TRUE), type = "p")

# What's in them?	
top.pc.10 <- names(sort(taxa_sums(ps_pc), TRUE)[1:10])
genuspc10 <- prune_taxa(top.pc.10, ps_pc)

# Exporting relative abundance table #
tax <- tax_table(genuspc10)
tax <- psmelt(tax)
write.csv(tax, file='taxa_PC.csv')

otus <- otu_table(genuspc10)
otus <- psmelt(otus)
write.csv(otus, file='otu_PC.csv') #Taxonomic plot of negative controls were performed in Excel